[workspace]
members = [
        "lampo-common",
        "lampod",
        "lampod-cli",
        "lampo-cli",
        "lampo-nakamoto",
        "lampo-jsonrpc",
        "lampo-client",
]
resolver = "2"
