[package]
name = "lampod"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.29.1", features = ["rt-multi-thread", "parking_lot"] }
lampo-common = { path = "../lampo-common" }
lampo-jsonrpc = { path = "../lampo-jsonrpc" }
lampo-client = { path = "../lampo-client" }
lightning = { git = "https://github.com/lightningdevkit/rust-lightning.git", features = ["max_level_trace"] }
lightning-block-sync = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-invoice = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-persister = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-background-processor = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-net-tokio = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-rapid-gossip-sync = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
log = "0.4.17"
time = "0.3.13"
bitcoin = "0.29.0"
futures = "0.3.28"
crossbeam-channel = "0.5.8"
once_cell = "1.17.1"
async-trait = "0.1.68"

[dev-dependencies]
lampo-nakamoto = { path = "../lampo-nakamoto" }
clightningrpc-conf = { git = "https://github.com/laanwj/cln4rust.git", branch = "master" }
lampo-bdk-wallet = { path = "../lampo-bdk-wallet" }
