[package]
name = "lampo-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
lampod = { path = "../lampod" }
tokio = { version = "1.22.0", features = ["rt"] }
clap = { version = "4.0.26", features = ["derive"] }
clightningrpc-conf = "0.0.1"
